version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "backend/"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "frontend/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "backend/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "production/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "node/"
    schedule:
      interval: "monthly"
