version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "monthly"
    groups:
      all-npm:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "backend"
    schedule:
      interval: "monthly"
    groups:
      all-go:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "frontend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "node"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "production"
    schedule:
      interval: "monthly"
