---
version: "3"

services:

  urdr:
    build:
      dockerfile: ../staging/Dockerfile
      context: ../backend
    volumes:
        - ../backend/sql:/app/
    container_name: urdr
    expose:
      - "8080"
    ports:
      - 8080:8080
    restart: always
    env_file:
      - ./urdr.env

volumes:
  exclude: null
