---

version: '3'

services:
  postgres:
    restart: always
    image: postgres:12
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - type: bind
        source: ./initdb.d/
        target: /docker-entrypoint-initdb.d/
    env_file:
      - .postgres.env
    networks:
      - "urdr-net"
  redmine:
    restart: always
    image: redmine:4.2.3
    volumes:
      - type: bind
        source: ./redmine-data/plugins/
        target: /usr/src/redmine/plugins/
      - type: bind
        source: ./redmine-data/files/
        target: /usr/src/redmine/files/
      - type: bind
        source: ./configuration.yml
        target: /usr/src/redmine/config/configuration.yml
      - type: bind
        source: ./secrets.yml
        target: /usr/src/redmine/config/secrets.yml
      - type: bind
        source: ./redmine-data/mails/
        target: /usr/src/redmine/tmp/mails/
    ports:
      - 3000:3000
    env_file:
      - .redmine.env
    networks:
      - "urdr-net"
  nginx-mails:
    restart: always
    build: email-monitor/
    volumes:
      - type: bind
        source: ./redmine-data/mails
        target: /opt/mails
    ports:
      - 3001:80
    networks:
      - "urdr-net"

volumes:
  postgres-data:

networks:
  urdr-net:
    external: true
