---
version: "3"

services:

  urdr:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
      - ./urdr.env:/app/urdr.env
    container_name: urdr
    expose:
      - "8080"
    ports:
      - 8080:8080
    restart: always
    env_file:
      - ./urdr.env

  node-urdr:
    container_name: node-urdr
    env_file:
      - ./urdr.env
    environment:
      - NODE_OPTIONS="--max-old-space-size=2048"
   
    build:
      context: ./
      dockerfile: ./node/Dockerfile
    command: bash -c "rm -rf /home/node/app/node_modules/* && npm run start"
    volumes:
      - ./frontend:/home/node/app/
      - exclude:/home/node/app/node_modules
    ports:
      - 4242:4242

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 4567:80

volumes:
  exclude: null
