---
version: "3"

services:

  urdr:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
      - ./urdr.env:/app/urdr.env
    container_name: urdr
    expose:
      - "8080"
    ports:
      - 8080:8080
    restart: always
    env_file:
      - ./urdr.env

  node-urdr:
    container_name: node-urdr
    build:
      context: ./
      dockerfile: ./node/Dockerfile
    command: bash -c "rm -rf /home/node/app/node_modules/* && export SNOWPACK_PUBLIC_API_URL=${BACKEND_HOST}:${BACKEND_PORT} && npm run start"
    volumes:
      - ./frontend:/home/node/app/
      - exclude:/home/node/app/node_modules
    ports:
      - 4242:4242
    environment:
      - NODE_OPTIONS="--max-old-space-size=2048"
    env_file:
      - ./urdr.env

volumes:
  exclude: null
