---

services:

  urdr:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
      - ./urdr.env:/app/urdr.env
      - cache:/tmp/.cache
    container_name: urdr
    expose:
      - "8080"
    ports:
      - 8080:8080
    restart: always
    env_file:
      - ./urdr.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger/"]
      interval: 10s
      timeout: 3s
      retries: 60  # 10s * 60 = 10 minutes

  node-urdr:
    container_name: node-urdr
    env_file:
      - ./urdr.env
    environment:
      - NODE_OPTIONS="--max-old-space-size=2048"
    depends_on:
      urdr:
        condition: service_healthy

    build:
      context: ./
      dockerfile: ./node/Dockerfile
    command: sh -c 'rm -rf /home/node/app/node_modules/* && npm run start'
    volumes:
      - ./frontend:/home/node/app/
      - exclude:/home/node/app/node_modules
      - .git:/home/node/app/.git

  nginx:
    image: nginx:1.25.1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 4567:80
    depends_on:
      urdr:
        condition: service_healthy
      node-urdr:
        condition: service_started

volumes:
  exclude: null
  cache:
