version: '3'

services:
  urdr:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/app
    container_name: urdr
    expose:
      - "8080"
    ports:
      - 8080:8080
    restart: always
    env_file:
      - ./backend/.env

  node-urdr:
    container_name: node-urdr
    build:
      context: ./
      dockerfile: ./node/Dockerfile
    command: bash -c "rm -rf /home/node/app/node_modules/* && npm run start"
    volumes:
        - ./frontend:/home/node/app/
        - exclude:/home/node/app/node_modules
    ports:
      - 4242:4242
    environment:
        - NODE_OPTIONS="--max-old-space-size=2048"
volumes:
  exclude: