---
version: "3"

services:

  urdr:
    user: urdr
    image: ghcr.io/nbisweden/urdr:${TAG:?TAG-not-set}
    build:
      dockerfile: ../production/Dockerfile
      context: ../backend
      labels:
        - org.opencontainers.image.source="https://github.com/NBISweden/urdr"
    volumes:
      - ../backend/:/app
    container_name: urdr
    expose:
      - "8080"
    ports:
      - 8080:8080
    restart: always
    env_file:
      - ./urdr.env
  nginx:
    image: ghcr.io/nbisweden/urdr-web:${TAG:?TAG-not-set}
    container_name: urdr-frontend
    build:
      dockerfile: ../production/Dockerfile.nginx
      context: ../frontend
      labels:
        - org.opencontainers.image.source="https://github.com/NBISweden/urdr"
      args:
        - SNOWPACK_PUBLIC_API_URL=${SNOWPACK_PUBLIC_API_URL}
        - SNOWPACK_PUBLIC_REDMINE_URL=${SNOWPACK_PUBLIC_REDMINE_URL}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 4567:80

volumes:
  exclude: null
