basePath: /
definitions:
  api.Activity:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  api.Entry:
    properties:
      activity:
        $ref: '#/definitions/api.Activity'
      issue:
        $ref: '#/definitions/api.Issue'
    type: object
  api.Issue:
    properties:
      id:
        type: integer
      subject:
        type: string
    type: object
  api.PriorityEntry:
    properties:
      activity:
        $ref: '#/definitions/api.Activity'
      custom_name:
        type: string
      is_hidden:
        type: boolean
      issue:
        $ref: '#/definitions/api.Issue'
    type: object
  api.user:
    properties:
      login:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: National Bioinformatics Infrastructure Sweden
    url: https://www.nbis.se
  description: This is the Urdr API.
  title: Urdr API
  version: "1.0"
paths:
  /api/activities:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Proxy for the "/enumerations/time_entry_activities.json" Redmine endpoint
  /api/issues:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Proxy for the "/issues.json" Redmine endpoint
  /api/login:
    post:
      consumes:
      - application/json
      description: Log in a user using the Redmine API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.user'
        "401":
          description: Unauthorized
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - BasicAuth: []
      summary: Log in a user
  /api/logout:
    post:
      consumes:
      - application/json
      description: Log out a user by destroying the session
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Log out a user
  /api/priority_entries:
    get:
      consumes:
      - application/json
      description: Get the favorites and hidden issues for the current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.PriorityEntry'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get priority entries (favorites or hidden issues)
    post:
      consumes:
      - application/json
      description: Stores the favorites and hidden issues for the current user
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Store priority entries (favorites or hidden issues)
  /api/recent_issues:
    get:
      consumes:
      - application/json
      description: Get recent issues that the user has spent time on
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Entry'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get recent issues
  /api/time_entries:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Proxy for the "/time_entries.json" Redmine endpoint
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create, update, or delete a time entry
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
