---
name: API docs

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.23]
    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get swag
        run: |
          go get github.com/swaggo/swag/gen@v1.8.5
          go get github.com/swaggo/swag/cmd/swag@v1.8.5
          go install github.com/swaggo/swag/cmd/swag@v1.8.5
        working-directory: backend

      - name: Check that docs can be created
        run: swag init -g api/api.go
        working-directory: backend
