name: Create packages
on:
  push:
    branches:
      - main


jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push images
        working-directory: production
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          GHCR_USER: ${{ secrets.GHCR_USER }}
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
             echo "${GHCR_PAT}" | docker login ghcr.io -u "${GHCR_USER}" --password-stdin

             branch=${GITHUB_REF##*/}

             for image in urdr urdr-web; do
               docker pull "ghcr.io/nbisweden/$image:latest" || true
               docker pull "ghcr.io/nbisweden/$image:$branch" || true
             done

             cat > urdr.env <<END
             BACKEND_DB_PATH="./database.db"
             BACKEND_HOST=0.0.0.0
             BACKEND_PORT=8080
             REDMINE_URL="https://projects.nbis.se"
             SESSION_DB_PATH="./session.db"
             SNOWPACK_PUBLIC_API_URL="https://urdr.nbis.se"
             SNOWPACK_PUBLIC_REDMINE_URL="https://projects.nbis.se"
             END

             docker-compose --env-file urdr.env build --build-arg BUILDKIT_INLINE_CACHE=1

             for image in urdr urdr-web; do
               docker tag "$image:latest" "ghcr.io/nbisweden/$image:$branch"
               docker push "ghcr.io/nbisweden/$image:$branch"
               docker tag "$image:latest" "ghcr.io/nbisweden/$image:latest"
               docker push "ghcr.io/nbisweden/$image:latest"
             done
