---
name: golangci-lint
on:
  pull_request:
    paths:
      - backend/**
permissions:
  contents: read
jobs:
  golangci:
    name: go-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: backend
          args: --timeout=5m
